### ISSUE TITLE
Linting Errors as PR Comments

### ISSUE THREAD

**Issue by SethFalco** [EbookFoundation/free-programming-books#4416]
I think it'd be worth pulling the lint summary from CI and posting them as a comment in the PR?

Many contributors either don't know how or don't bother to check the failed checks. And some that do, don't understand what's wrong because they're only reading the bottom line, or just don't know what to focus on.

It'd massively reduce the workload of maintainers to push the warnings to a PR comment, so the relevant information that contributors need is readily available.

**Comment by SethiPandi** [comment]
I've been playing around with it a fair bit and came up with this so far. :thinking: 

**.travis-ci.yml**
```yml

language: shell
dist: xenial
os: linux

jobs:
  include:
    -
      language: node_js
      node_js:
        - 6
      before_script:
        - npm install -g free-programming-books-lint
      script:
        - set -o pipefail; fpb-lint . |& tee output.txt
      after_failure:
        - |
          message="The following failures occurred when linting on Travis CI:\n\n$(cat output.txt)"
          message_escaped=$(echo ${message} | sed -n ':a; $ ! {N;ba}; s/\n/\\n/g;p')
          
          if [ "${TRAVIS_PULL_REQUEST}" != "false" ] ; then
            curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d "{\"body\":\"${message_escaped}\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
          fi
```
> Will need to add an environment variable to the GitHub access token to an account in order for it to post a comment.

**Result on Failure**
![image](https://user-images.githubusercontent.com/22801583/96452265-14f4c500-1219-11eb-88cb-9e76f358a008.png)
> Does nothing when the build succeeds, and only acts on Pull Requests. ^I was lazy, that is automated, I just used a personal access token rather than creating a seperate bot account for it.

**Comment by eshellman** [comment]
That would be useful I think. Might be helpful to look at history https://github.com/EbookFoundation/free-programming-books/issues?q=is%3Aissue+linter

**Comment by SethiPandi** [comment]
If I understand, it should be possible to stop using Travis, and favor GitHub Actions entirely, correct?
Is there any preference on this; are we're using Travis CI for any particular reason, or is it just what the repository had before? 

I want to dive more into this and implement it soon, but I just wanted to check if there's any interesting shifting the linting to GitHub Actions first is all.

Not only to show users warnings, but so users don't end up worrying about failures which aren't their fault. ie https://github.com/EbookFoundation/free-programming-books/pull/4569#issuecomment-714426400

It'll be nice to wrap some information around it, ie if the warnings are referring to files you didn't change, a failing PR may have accidentally been merged. They can either leave it, or update their PR to help clean up those issues too.

**Comment by eshellman** [comment]
I think @borgified looked at some of these issues.

**Comment by borgified** [comment]
hi @SethiPandi i see you noticed we use both travisci and github actions. there's no real reason why we couldn't consolidate to one. i only added the github actions cuz i wanted to learn how to use it. im more familiar with travisci but i think github actions is better integrated to github for obvious reasons.

to your point of wanting to bring the output of the build (in this case, the reasons why a PR failed the checks), if you want to do some digging, there's a way to do it that should already work. just need to implement it/test it to make sure. i'll drop some links for you to get you started in the right direction.

so for example, let's take a recent PR's check: https://github.com/EbookFoundation/free-programming-books/pull/4873/checks?check_run_id=1325849656#step:6:10

we want to surface this output to a more convenient location in the PR, perhaps as a comment. here's one way that this can be done:

see this section about integrating Danger to awesome_bot : https://github.com/dkhamsing/awesome_bot#danger

if i remember correctly, we're already generating the json files (see artifacts) so all we have to do is hook this up (create the Dangerfile and modify github actions to use Danger) and we'll get the nice looking report automatically.

as for the fpb-lint currently running in travisci, i'd say the best way would be to migrate that over to github actions, then employ the same method with Danger to put that in the report too. (prob just need to figure out the format of the json file and generate one)

**Comment by SethiPandi** [comment]
@borgified 

Understood, and thank you for the links.

This looks pretty cool. :thinking: 
The only unfortunate part is, I was hoping we could actually have it automatically do a review and suggestions, rather than just drop a comment. And only really comment for things that isn't a same line fix, ie alphabetical order, wrong number of line breaks etc

```diff
- * [My Link] (https://example.com)
+ * [My Link](https://example.com)
```
> `(\[.+\])\s+(\(.+?\))` -> `$1$2`

```diff
- * [My Link](https://example.com/)
+ * [My Link](https://example.com)
```
> `\((https?:\/\/[a-zA-Z\d.-]+)\/\)` -> `\($1\)`

```diff
- * [My Link](https://example.com/)  - Seth
+ * [My Link](https://example.com/) - Seth
```
> `\s+-\s+` -> ` - `

It would add some logic, but these kinds of things should be easy to fix with a some regex replacements.
The example rules I wrote above are probably kind of crap, but they were quick examples that don't cause any issues in `free-programming-books.md` at least.

This would maximize convenience for contributors, give them the exact change that needs to be made if they aren't sure, and give them a "Commit" button for convenience, so it's easy to integrate the change without the review.

**Comment by davorpa** [comment]
I found this both snippets that could help using github actions:

- https://rammusxu.github.io/toolkit/snippets/github-action/#get-other-step-output-as-enviroment-in-github-script
- https://rammusxu.github.io/toolkit/snippets/github-action/#create-a-comment-in-pull-request

Basically
- Monitor exitcode of linting step
- If distinct than 0 then there are errors. Save error stream output as action env-var
- Submit a comment using action-script loading that variable as body in next step

**Comment by SethFalco** [comment]
I've looked into this a little. I think my favorite solution would be split into 2 steps.

There can be a bot on GitHub for Free Ebook Foundation, probably something like ebook-foundation-bot.
This will be easy to do using GitHub Actions and GitHub CLI which is pre-installed in all cloud hosted runners.

### Step 1
This can be done immediately, we just extend the fpb-lint GitHub Action to post a comment if the PR fails.
What it sends is up for discussion.

* Tell the user that the build failed and prompt them to check the output?
* Forward the output of the build as a comment?
* Send a bunch of diffs with the changes the user should make to get it passing? (Not suggestions/reviews!)

This can be done in CLI with `gh pr review --body {} --request-changes`.

This will be simpler if we can have the linting under a single process, output, and exit code.
* https://github.com/vhf/free-programming-books-lint/pull/29

### Step 2
Once https://github.com/cli/cli/issues/4056 has been resolved, we'll be able to make suggestions directly from CLI.
To me, it doesn't seem worth creating a custom solution for this from scratch for now. It'll be super easy when or if this is addressed.

Once this is done, we can just write a few commands using [sed](https://www.gnu.org/software/sed/manual/sed.html) and do the command to post a review with the suggestions.

If it takes too long, I can make a GitHub Action that suggests uncommitted changes as a review, but we'll see. (Alternatively, maybe it's about time I learned Go. ^-^')

**Comment by eshellman** [comment]
Ok, so what do I need to do?

**Comment by SethFalco** [comment]
I was originally going to say that we'd need a bot user, kind of like [tldr-bot](https://github.com/tldr-bot), which is a bot for another organization.

However, it looks like when using GitHub CLI there's actually no need to even go through a user.

![image](https://user-images.githubusercontent.com/22801583/134893502-d7f02f30-85ac-4402-a58c-bb64c62d92e1.png)

We can make the pipeline approve or request changes on behalf of fpb-lint as is, it'll be sent by the default github-actions bot user.

With this in mind, I don't think you'd need to do anything:
* We need to remove Travis. (`.travis.yml`)
* Update all Docs (Translations will have to be done overtime?)
* Deciding what the GitHub Action should post on success and failure. (We can discuss in the PR I'll open later today.)

In the future, but not in time for this year's Hacktoberfest we can make the more fancy suggestion solution. (Likely as a dedicated GitHub App that suggests uncommitted changes after a GitHub Action)

**Comment by SethFalco** [comment]
```yaml
name: free-programming-books-lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        git clone https://github.com/SethFalco/free-programming-books-lint.git
        cd free-programming-books-lint
        git checkout origin/multiple-dirs
        npm i
        npm i -g .
    - run: fpb-lint books casts courses more
      if: github.event_name == 'push'
    - run: |
        fpb-lint books casts courses more 2>&1 | tee output.log
        result_code=${PIPESTATUS[0]}

        if [ $result_code != 0 ]
        then
          gh pr review $PR --body "The build failed with the following output:
          \`\`\`
          $(cat output.log)
          \`\`\`" --request-changes
        else
          gh pr review $PR --approve
        fi

        exit $result_code
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.html_url }}
```

The updated GitHub workflow should look something like this.
The first `run` will need to change when/if my PR to fpb-lint is merged and published, using my fork is temporary.

If linting fails, it'll request changes and post the output of the linter.
If linting passes, it'll approve the changes (not merge) with no message. (We should probably add a message specifying it's only considering fpb-lint. It doesn't consider other human input or the URL checks.)

We can discuss the desired behavior.
