### ISSUE TITLE
feat: Create Github Actions to auto manage some labels

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#7024]
It will be great that when a PR is merged doing some actions

How to handle it: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

**`pr-merged.yml`**:
```yml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

Then we need:

1. Is this usefull?
2. Decide which labels manage. E.g.: remove `Waiting for changes`, `stale`...
3. ...
